apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/component: webhook
resources:
  - ../../configurations/prometheus-operator
  - clusterrole.yaml
  - config-leader-election.yaml
  - hpa.yaml
  - role.yaml
  - serviceaccount.yaml
  - servicemonitor.yaml
  - webhook.yaml
  - webhooks.yaml
images:
  - name: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/webhook
    newTag: v0.62.1@sha256:5e4ecb3ecf6a902a90d550d93ba0edf51160f24f432e958591b43d29469781a1
