apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/component: controller
resources:
  - ../../configurations/prometheus-operator
  - clusterrole.yaml
  - config-leader-election.yaml
  - controller.yaml
  - podmonitor.yaml
  - role.yaml
  - serviceaccount.yaml
patches:
  - # Let's keep all the images here in the kustomization file
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: tekton-pipelines-controller
      spec:
        template:
          spec:
            containers:
              - name: tekton-pipelines-controller
                env:
                  - name: ENTRYPOINT_IMAGE
                    # renovate: datasource=docker
                    value: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/entrypoint:v0.63.0@sha256:d83f21f007858846568cb9eaef6c6db89822561bb94545c2f34f3e3ff6b266be
                  - name: NOP_IMAGE
                    # renovate: datasource=docker
                    value: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/nop:v0.63.0@sha256:678ae13d51f52c33228b800dcb7e2ac855cc8c8c2179c4a90dff96a07a2bd1b9
                  - name: SIDECARLOGRESULTS_IMAGE
                    # renovate: datasource=docker
                    value: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/sidecarlogresults:v0.63.0@sha256:cc7ccb187f7899ad86f0e5a533980aa3bb11f5a90b032a446a5bbaca801fad8f
                  - name: WORKINGDIRINIT_IMAGE
                    # renovate: datasource=docker
                    value: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/workingdirinit:v0.63.0@sha256:2de54fdd1fe956d38b65073cb8f891513d4f613793d093cd2406811b2af077b9
                  - name: SHELL_IMAGE
                    # renovate: datasource=docker
                    value: cgr.dev/chainguard/busybox:latest@sha256:19f02276bf8dbdd62f069b922f10c65262cc34b710eea26ff928129a736be791
                  - name: SHELL_IMAGE_WIN
                    # renovate: datasource=docker
                    value: mcr.microsoft.com/powershell:nanoserver@sha256:b6d5ff841b78bdf2dfed7550000fd4f3437385b8fa686ec0f010be24777654d6
images:
  - name: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/controller
    newTag: v0.63.0@sha256:fd66b42c1076dec4430ab6767919e56c95b6a547c9696c40e06329c7b3b932ba
